### ISSUE TITLE
evil-mode

### ISSUE THREAD

**Issue by unforgettableid** [sanel/dotfiles#2]
Just curious:  have you ever tried [evil-mode](http://www.emacswiki.org/emacs/Evil)?  It's a vim emulation mode.  Word on the street is that it's even better than viper-mode.

**Comment by sanel** [comment]
If you look at my `init.el`, you'll see I'm using evil-mode :)

I presume you noticed `vimlike.el`, which I'm using for speed comparison against evil-mode.

**Comment by unforgettableid** [comment]
Ah.  Indeed I looked at `vimlike.el` and indeed I don't think I looked at your `init.el` file.  :)
